apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeradius-test
  namespace: freeradius-experimentation
  labels:
    app: freeradius
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeradius
  template:
    metadata:
      labels:
        app: freeradius
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: freeradius
          image: ghcr.io/andrewnicolalde/homelab-nacl/freeradius:latest
          args: ["-X"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: radsec
              containerPort: 2083
              protocol: TCP
            - name: radius-auth
              containerPort: 1812
              protocol: UDP
            - name: radius-acct
              containerPort: 1813
              protocol: UDP
          volumeMounts:
            - name: certs
              mountPath: /etc/raddb/certs/ca.crt
              subPath: ca.crt
              readOnly: true
            - name: certs
              mountPath: /etc/raddb/certs/ca.pem
              subPath: ca.pem
              readOnly: true
            - name: certs
              mountPath: /etc/raddb/certs/server.crt
              subPath: server.crt
              readOnly: true
            - name: certs
              mountPath: /etc/raddb/certs/server.key
              subPath: server.key
              readOnly: true
            - name: certs
              mountPath: /etc/raddb/certs/server.pem
              subPath: server.pem
              readOnly: true
            - name: config
              mountPath: /etc/raddb/clients.conf
              subPath: clients.conf
              readOnly: true
            - name: config
              mountPath: /etc/raddb/mods-enabled/eap
              subPath: eap
              readOnly: true
            - name: config
              mountPath: /etc/raddb/mods-config/files/authorize
              subPath: authorize
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: freeradius-certs
            defaultMode: 0440
        - name: config
          configMap:
            name: freeradius-config
            defaultMode: 0440
