apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: freeradius-experimentation

resources:
  - 00-namespace.yaml
  - 01-deployment-test.yaml
  - 02-service.yaml

secretGenerator:
  - name: freeradius-certs
    literals:
      - ca.crt="PLACEHOLDER_REPLACE_IN_OVERLAY"
      - server.crt="PLACEHOLDER_REPLACE_IN_OVERLAY"
      - server.key="PLACEHOLDER_REPLACE_IN_OVERLAY"
      - ca.pem="PLACEHOLDER_REPLACE_IN_OVERLAY"
      - server.pem="PLACEHOLDER_REPLACE_IN_OVERLAY"

configMapGenerator:
  - name: freeradius-config
    files:
      - clients.conf=./config/clients.conf.example
      - eap=./config/eap
      - authorize=./config/authorize.example
